### PR TITLE
Caching property with more tests added

### PR DESCRIPTION
**Pull request by jtrain**
I've added some tests that include view access with nested serializers

### CODE REVIEW

**Comment by jtrain** [comment]
@dbrgn The tests were extended to include views.py and the models have additional fields. No changes were made to the source for dynamic fields.

I can't see any problem so far with the tests supplied.

I'll also try in our production code and report back.

**Comment by jtrain** [comment]
extends #33 to include more testing.

**Comment by dbrgn** [comment]
Great, thank you! Do you think this is ready for merging (and a new release)?

PS: I like that you used `black` on the test file, but the following commit adds non-conforming code style again 🙃 Maybe black could be applied to all source files, and included in CI.

(Speaking of which, this currently seems broken. I'll try to fix it.)

**Comment by dbrgn** [comment]
@jtrain I fixed CI on the master branch. Could you rebase your branch? (Let me know if you need help with that.)

**Comment by jtrain** [comment]
Regarding the introducing non conforming code style, my default editor set up is black being run on save. It looks like my configuration for black is being run (double quotes, not single quotes etc).

It could be that we are using different black set ups.

Also I am so used to using black that I forgot that i probably shouldn't have used it on a public project like this. I could turn it off in future if the auto-formatting is a problem.

I'd be happy to have black on all files, and included in CI, definitely fits my style (which is to accept black's style :D)

**Comment by jtrain** [comment]
Rebased and ready to go.

I believe the cached_property will introduce a problem when the same serializer instance is used in multiple contexts. For example if a serializer were instantiated and the `fields` attribute were accessed, and then later the same instance is edited to include a different `request` and `fields` was to be re-accessed. 

I think that sounds contrived. I don't see how anyone would be doing something like that. The normal way would be that the serializer instance lives for the duration of the request, and the `.context['request']` value is left unchanged. A different request (or nesting level) is a completely new serializer instance.

**Comment by jtrain** [comment]
I've added one more test that highlights how the `fields` attribute will not change despite the `request` being changed.

This is now the expected behavior. 

We don't have any code that does this. I don't know why someone would do that either.

**Comment by dbrgn** [comment]
Thanks @jtrain!

**Pull request merged**
